[project]
name = "ros2-robotics-course"
version = "0.1.0"
description = "Notebooks for the ROS2 Robotics Course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "nbdev>=3.0.12",
]
